platform :ios, '9.0'

target 'GraduationDesign' do
    pod 'Masonry'
    pod 'Mantle'
    pod 'YYText'
    pod 'MJRefresh'
    pod 'AFNetworking'
    pod 'SDCycleScrollView'
    pod 'Toast', '~> 4.0.0'
end
